/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rockethorse;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String args[]) {
        Chessboard board = new Chessboard();
        board.print(Piece.Color.WHITE);
        board.print(Piece.Color.BLACK);
    }
}
